### ISSUE TITLE
Sketch cloud

### ISSUE THREAD

**Issue by jacboy** [weg-li/weg-li-ios#16]
> From 29 April 2020, we’re changing the format of Cloud document URLs to make them more secure. After this time, the URL you send to others when you share a Cloud document with will be different.
Don’t worry — URLs with the old format will still work and redirect for a while, but we’ll phase these out by October 2020. Before then, be sure to update any links or bookmarks where you use a Cloud document URL.

If you have any questions, please speak to our Customer Service team for support.

See: https://updates.sketch.cloud/we-re-changing-cloud-document-urls-143867

Todo: update Sketch cloud link.

**Comment by mltbnz** [comment]
Do I need to be the owner of the project to see the new structure?

**Comment by jacboy** [comment]
I don't know :(
