### ISSUE TITLE
add a readme

### ISSUE THREAD

**Issue by phoet** [weg-li/weg-li-ios#3]
as a curious person browsing this repository i would like to have a readme that includes:

* the basic concept of the app
* matching screenshots
* installation & build instructions
* further information if available (list of issues, roadmap etc)

**Comment by mltbnz** [comment]
@phoet Maybe you could add the basic concept of the app to #7 or after that one is merged

**Comment by phoet** [comment]
@mltbnz i was not involved in building any of this :) i don't even know swift...

@mnin could you take care of this?

**Comment by mltbnz** [comment]
Thats fine. Its just a readme :)

**Comment by mltbnz** [comment]
Gonna close this since there is a Readme 🍾
