### ISSUE TITLE
Use gender-neutral, non-binary inclusive language in e-mail templates

### ISSUE THREAD

**Issue by ComFreek** [weg-li/weg-li-ios#48]
https://github.com/weg-li/weg-li-ios/blob/e26927cb0f0a37573d9733ea491508b6e95ad354/WegliKit/Sources/ReportFeature/Report%2BMail.swift#L9

The above language constructs unnecessarily assume a binary world view, that every human either identifies as a woman or man. This is not the case and people feel excluded. Moreover, bringing up gender in an impersonal salutation is unnecessary, in my opinion.

The Internet offers many alternatives. Personally, in the context of wegli I'd like `Sehr geehrte Lesende` or `Sehr geehrte Zuständige`.

Related issues: https://github.com/weg-li/weg-li/issues/546 https://github.com/weg-li/weg-li-android/issues/17

**Comment by mltbnz** [comment]
I think that is a good idea. Would merge that

**Comment by ComFreek** [comment]
Great! I've just created PRs for all respective repos/issues.
