### ISSUE TITLE
add option to view uploaded image in large size

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#51]
iOS 15.4.1
weg-li 1.0.18

**Currently**
After a photo is uploaded it is shown in small size with a trash can icon over it to remove it.

**Expected**
There should be a way to view selected photos in large size since otherwise it is difficult to fill the requested details.

![1](https://user-images.githubusercontent.com/5708172/162590252-4bb17cce-c28d-452a-b397-5d763f12476d.jpg)

**Comment by mltbnz** [comment]
Could also be a context menu I guess 👍

**Comment by foss-** [comment]
Thanks for adding an option to view the image. This currently works by long pressing the image and selecting `Ansehen`. However the image then presented cannot be zoomed and on a small mobile screen that may result in situations with the numbers plate being much too small to be read by a human.

Can you add pinch to zoom for the image view?

**Comment by mltbnz** [comment]
Would be nice I guess. I'll take a look

**Comment by foss-** [comment]
iOS 15.4.1
weg-li 1.0 (23)
verified
