### ISSUE TITLE
reading geo location from photo not functional

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#52]
iOS 15.4.1
weg-li 1.0.18

**Curently**
Despite the photo heaving geo data it is not read in weg-li app.

**Comment by mltbnz** [comment]
I know there are some images that don't quite work. Can your attach an example image maybe so that I can take a look?

**Comment by foss-** [comment]
You've got mail.

**Comment by mltbnz** [comment]
Can't reproduce. Works over here. Please share some more info or an example image here

**Comment by foss-** [comment]
another test file sent
