### ISSUE TITLE
return to main view after sucessfully sending complaint via email

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#53]
iOS 15.4.1
weg-li 1.0.18

**Currently**
After the complaint is sent via email, weg-li is still on the view of the complaint which just has been sent. Info message shows to fill all details and complains about missing image, location and description.

**Expected
After successfully sending complaing via email, return to default view or maybe better show overview of sent complaints.

**Comment by mltbnz** [comment]
Hi. There is an issue with the Mail composer that comes with iOS which is that i don't know if the Mail was really sent or the user cancelled. At least I get the same result and so to be safe I leave the user on the report view. At least that is how I remember it 😄 But I'm general I agree. Maybe I'll give it another go

**Comment by mltbnz** [comment]
cb2afb3591737e266c7bec86f24caa7188ff0d65

**Comment by foss-** [comment]
iOS 15.4.1
weg-li 1.0 (23)
verified
