### ISSUE TITLE
app crashes when no email account is configured in mail app

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#54]
iOS 15.4.1
weg-li 1.0.18

**Currently**
In case the user has no email account configured in mail app, weg-li shows a warning about being unable to send the complaint. That is a nice start. However, the app crashes when user clicks on send.

**Expected**
Either grey out the button so that it is unclickable *until* an email account is configured in mail app and / or show a clear error dialog once the user clicks send and prevent the app from crashing to escape the situation more gracefully.

**Comment by mltbnz** [comment]
Good point. I'd present an alert now maybe with the option to copy the email parts

**Comment by foss-** [comment]
Fixed in https://github.com/weg-li/weg-li-ios/commit/cb2afb3591737e266c7bec86f24caa7188ff0d65 
Verified in 1.0.20.
