### ISSUE TITLE
image selection not uploaded on first attempt

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#55]
iOS 15.4.1
weg-li: 1.0.18

1. select `Fotos auswählen`
2. select image
3. click `Add`

**Currently**

No photo is showing up in fotos section. After repeating the steps a second time the image is uploaded as expected.

**Expected**

Image upload should work on first attempt.

**Comment by mltbnz** [comment]
could you also provide the version you are using? you can find it in the settings
