### ISSUE TITLE
Date or timestamp not read from metadata / no option to adjust date of incident

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#56]
- [ ] timestamp not read from metadata
- [x] no option to adjust date of incident

When filing a complaint after uploading an image the date of incident is not read from image metadata. Also there is no field to adjust this essential information.

This is highly problematic since currently the timestamp of the time, the complaint is filed, is used.

This qualifies as a blocker I guess.

**Comment by mltbnz** [comment]
good point. think I was always under the impression that someone files a complaint "on the go" so the date is equal to when a new report gets drafted. But a scenario could be that someone does that the next day or so. you would have to update that info in the mail currently

**Comment by foss-** [comment]
Wouldn‘t the easiest solution be, to just read the images metadata? That covers both use-cases.

If this does not make it for the intial release I would assume quite some confusion on user side, since weg li webservice reads from files meradata and user probably have come to expect this to be the default.
Considering the nature of the complaint and accuracy being rather important if the case goes to trial, I‘d still consider this a show stopper.

**Comment by phoet** [comment]
I agree with @foss- 

a) the date should always be editable

**Comment by foss-** [comment]
Thanks for addressing `no option to adjust date of incident`.

In my test with 1.0.20 `timestamp not read from metadata` is persisting.

**Comment by mltbnz** [comment]
Works on my machine...
![image](https://user-images.githubusercontent.com/14075359/163194905-6a3bbd64-1bdd-4f8e-9c74-97c4b0460490.png)

You have another example?

**Comment by foss-** [comment]
You got mail.

**Comment by mltbnz** [comment]
Persisting? Please share image if so. I'm on iOS 15.4.1 with the latest build and it works

**Comment by foss-** [comment]
for me with the test file I sent you, the time is not read.
