### ISSUE TITLE
Speed up data entry by automatically going up one level after a selection / entry has been made

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#57]
**Currently**

When data is entered, e.g. duration, the app moves up one level (expected).

However when doing the same selecting the kind of complaint being made, the view stays on that selection screen.

**Expected**

Once a complain is selected, it would be nice if the view also moved up one level.

**Comment by mltbnz** [comment]
closed by dadd6742e53459601643e92f7ba0711c2356681d

**Comment by foss-** [comment]
iOS 15.4.1
weg-li 1.0 (23)
verified
