### ISSUE TITLE
[feature] tapping image could show increased size image allowing users to verify license plate

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#72]
**Currently**

Users have to switch to fotos app to take a closer look at the selected image once selection has been made.

**Expected**

Adding an option to show increased image on tap would be helpful to verify whether OCR read the correct license plate info.

**Comment by mltbnz** [comment]
there is such a feature already when you long press on an image a context menu will be presented to trigger an option to look at the image
