### ISSUE TITLE
apple maps view lacking house numbers makes it hard to verify exact location

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#73]
**Currently**

Apple Maps is not showing house numbers, which makes it difficult to verify exact location.

**Expected**

When dropping a needle on a location not showing house number in Apple Maps on desktop, the house number is revealed. However that is not a solution to weg-li on iOS. Wondering if using OpenStreetMap would be the better approach? Or if Apple Maps view can be taught to show house numbers by default inside of weg-li.

**Comment by louwers** [comment]
Consider switching to maplibre-gl-native :slightly_smiling_face:  https://github.com/maplibre/maplibre-gl-native

**Comment by mltbnz** [comment]
it looks interesting
