### ISSUE TITLE
„Meldungen“ show „Error loading notices“

### ISSUE THREAD

**Issue by HerMatth** [weg-li/weg-li-ios#82]
After installing Weg-li on iPhone11 with OS 16.3.1 the Tab „Meldungen“ lists my former cases (correct summary) - but without any data. Also in bottom it will shown the error: „Error loading notices“

The Weg-li Account has been linked correctly with API-Token. 

![785CB345-7FC6-4890-916F-B79FEDAE87B0](https://user-images.githubusercontent.com/128574912/226820882-cc4551f7-728d-4e40-9f56-0ec0d9c36b80.png)
![E22C8592-997B-4720-AA45-95BA0619C9DB](https://user-images.githubusercontent.com/128574912/226821082-8c4f8d55-b039-401a-acd5-5bcd8be3ffd7.png)

**Comment by mltbnz** [comment]
Thanks for reaching out. I also noticed that recently and later saw that some parts of the API have changed.
https://twitter.com/weg_li/status/1637010026001846272?s=20

I will get to it as soon as possible

**Comment by mltbnz** [comment]
I pushed the update today. Should work again

**Comment by mltbnz** [comment]
I forgot something. The code on GitHub works again but I'm still in app review so AppStore is still broken atm
