### ISSUE TITLE
Parken für E-Fahrzeuge

### ISSUE THREAD

**Issue by Ruediger-P** [weg-li/weg-li-ios#84]
Hallo, es gibt Parkplätze nur für Elekto-PKWs, aber ohne Lademöglichkeit. Die fehlen in der Aufstellung möglicher Parkverstösse.

**Comment by phoet** [comment]
Welche TBNR soll dieser Verstoß haben?

**Comment by Ruediger-P** [comment]
Hallo,TBNR? 😳— Mit nettem GrussRüdiger Prenzel-mobil-Am 22.06.2023 um 22:49 schrieb Peter Schröder ***@***.***>:﻿
Welche TBNR soll dieser Verstoß haben?

**Comment by phoet** [comment]
Was genau soll mir das sagen?

**Comment by Ruediger-P** [comment]
Das ich nicht weiß, was TBNR bedeutet…Ok, ich kann mal googeln — Mit nettem GrussRüdiger Prenzel-mobil-Am 23.06.2023 um 11:26 schrieb Peter Schröder ***@***.***>:﻿
Was genau soll mir das sagen?

**Comment by Ruediger-P** [comment]
Ich habe gegoogelt. Keine Ahnung. Es gibt bei uns Parkplätze, die, ähnlich wie Parkplätze für Behinderte, ein Hinweisschild mit einem Symbol für Elektro-PKW haben (Auto mit kleinem Stecker- Schwänzchen). Dort parkende Normal PKW werden mit 55€ sanktioniert. Es gibt dort aber keine Ladesäule. Ich kann mir nicht vorstellen, das es das nur in Bochum gibt. — Mit nettem GrussRüdiger Prenzel-mobil-Am 23.06.2023 um 11:26 schrieb Peter Schröder ***@***.***>:﻿
Was genau soll mir das sagen?

**Comment by phoet** [comment]
Wir nehmen nur Verstöße auf, die im BKAT geführt werden.

**Comment by Ruediger-P** [comment]
— Mit nettem GrussRüdiger Prenzel-mobil-Am 23.06.2023 um 11:49 schrieb Peter Schröder ***@***.***>:﻿
Wir nehmen nur Verstöße auf, die im BKAT geführt werden.
