### ISSUE TITLE
Can't build in Xcode 15

### ISSUE THREAD

**Issue by dlpgithub** [weg-li/weg-li-ios#86]
Can't build in Xcode 15

<img width="1157" alt="Bildschirmfoto 2023-10-18 um 14 16 55" src="https://github.com/weg-li/weg-li-ios/assets/48456028/a7af28a0-2373-40e5-b0d5-b3cb0a65fde4">

**Comment by mltbnz** [comment]
I don't seem to have that issue. Ran it today with Xcode 15.1

Did you update any dependencies before compiling?

**Comment by dlpgithub** [comment]
Tried it today also with XCode 15.1.
Dependencies are up to date.

![Uploading Bildschirmfoto 2023-12-14 um 12.39.23.png…]()

**Comment by mltbnz** [comment]
Ok. I think those dependencies are actually not required to build the app. I meant the swift packages

**Comment by mltbnz** [comment]
The error from updating brew is a bit weird. Let me check if that's also happening here

**Comment by dlpgithub** [comment]
![Uploading Bildschirmfoto 2023-12-14 um 12.39.23.png…]()
