### ISSUE TITLE
No release version on (non-German) App Store, no TestFlight spots?

### ISSUE THREAD

**Issue by ratkins** [weg-li/weg-li-ios#88]
I couldn’t find a release version of the weg.li iOS app on the App Store (my App Store account is not German, if that matters) and the TestFlight isn’t accepting new users.

If the store is the problem, can you consider opening it up to non-German App Store account holders? There are a multitude of good reasons people who reside in Germany might not have a German App Store account and I can’t think of a good reason to not let them participate.

If it’s not on the store at all, can you open up TestFlight again? I see a bunch of the features I’d requested a while ago seem to have been implemented and I’d like to try it out again.

**Comment by phoet** [comment]
We dont have anyone maintaining the app currently as @mltbnz stepped down.
